### ISSUE TITLE
Linux game start fails

### ISSUE THREAD

**Issue by qubodup** [Panda3D-google-code-repositories/naith#1]
Hi, unfortunately running the game with Panda 1.9 fails when trying to load a level:

<pre>:task(error): Exception occurred in PythonTask Transition
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    run()
  File "/usr/share/panda3d/direct/showbase/ShowBase.py", line 52, in legacyRun
    builtins.base.run()
  File "/usr/share/panda3d/direct/showbase/ShowBase.py", line 2972, in run
    self.taskMgr.run()
  File "/usr/share/panda3d/direct/task/Task.py", line 503, in run
    self.step()
  File "/usr/share/panda3d/direct/task/Task.py", line 461, in step
    self.mgr.poll()
  File "/home/qubodup/naith-master/game/bin/manager.py", line 102, in transFrameLimiter
    for r in transTask(task):
  File "/home/qubodup/naith-master/game/bin/manager.py", line 73, in transTask
    for blah in self.addObj(obj):
  File "/home/qubodup/naith-master/game/bin/manager.py", line 172, in addObj
    for blah in inst.postInit():
  File "/home/qubodup/naith-master/game/plugins/include/include.py", line 35, in postInit
    for blah in self.manager.addObj(obj):
  File "/home/qubodup/naith-master/game/bin/manager.py", line 172, in addObj
    for blah in inst.postInit():
  File "/home/qubodup/naith-master/game/plugins/level/level.py", line 71, in postInit
    for i in self.postReload():
  File "/home/qubodup/naith-master/game/plugins/level/level.py", line 105, in postReload
    for r in odeSpaceHier.eggToOde(self.colEgg,surfaceType):
  File "/home/qubodup/naith-master/game/bin/shared/odeSpaceHier.py", line 39, in eggToOde
    for i in xrange(children.size()):
AttributeError: 'panda3d.core.NodePathCollection' object has no attribute 'size'</pre>

Any ideas?

**Comment by rdb** [comment]
Try changing it to:  for i, child in enumerate(children)

**Comment by qubodup** [comment]
This change:

<pre>diff --git a/game/bin/shared/odeSpaceHier.py b/game/bin/shared/odeSpaceHier.py
index 6394e35..8af0698 100644
--- a/game/bin/shared/odeSpaceHier.py
+++ b/game/bin/shared/odeSpaceHier.py
@@ -36,7 +36,7 @@ def eggToOde(np,surfaceType): # ,depth = 0
     #print ('|'*depth) + 'notgeom, ' + str(np.node().getClassType())
     # Check the children for useful data...
     children = np.getChildren()
-    for i in xrange(children.size()):
+    for i, child in enumerate(children):
       child = children[i]
       
       for r in eggToOde(child,surfaceType): # ,depth+1</pre>

solves the issue but another one occurs.

<pre>:task(error): Exception occurred in PythonTask Transition
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    run()
  File "/usr/share/panda3d/direct/showbase/ShowBase.py", line 52, in legacyRun
    builtins.base.run()
  File "/usr/share/panda3d/direct/showbase/ShowBase.py", line 2972, in run
    self.taskMgr.run()
  File "/usr/share/panda3d/direct/task/Task.py", line 503, in run
    self.step()
  File "/usr/share/panda3d/direct/task/Task.py", line 461, in step
    self.mgr.poll()
  File "/home/qubodup/src/git/naith/game/bin/manager.py", line 102, in transFrameLimiter
    for r in transTask(task):
  File "/home/qubodup/src/git/naith/game/bin/manager.py", line 73, in transTask
    for blah in self.addObj(obj):
  File "/home/qubodup/src/git/naith/game/bin/manager.py", line 168, in addObj
    inst = getattr(self.plugin[plugin],plugin)(self,element)
  File "/home/qubodup/src/git/naith/game/plugins/cullaabb/cullaabb.py", line 27, in __init__
    self.reload(manager,xml)
  File "/home/qubodup/src/git/naith/game/plugins/cullaabb/cullaabb.py", line 61, in reload
    for node in level.getByIsA('CullAABB'):
  File "/home/qubodup/src/git/naith/game/plugins/level/level.py", line 141, in getByIsA
    for i in xrange(col.size()):
AttributeError: 'panda3d.core.NodePathCollection' object has no attribute 'size'</pre>

Do you know what causes them? The changes in the Panda 1.9 api?

**Comment by rdb** [comment]
Yes, there is no more x.size(), you should use len(x) instead (or rather, iterate over the NodePathCollection as if it were a list), it's more Pythonic that way.

I didn't make this change on purpose though, it is merely a side effect of something I changed in interrogate (C++ size method maps to **len** slot directly).  Maybe I'll consider adding it back for 1.9.1, although I do think there should be only one way to do it, and there's no question that it should be len().

But ideally, the code should just be changed to iterate over the NodePathCollection directly.

**Comment by frainfreeze** [comment]
Reference shows int size() https://www.panda3d.org/reference/1.9.4/python/panda3d.core.NodePathCollection.php and suggests that its the same as get_num_paths()

if get_num_paths() is used error doesn't pop up. ada563c7901621618c2438fc95197d4c16fb279c

Sorry for late reply.
